package ma.entraide.handicap;

import ma.entraide.handicap.Entity.Province;
import ma.entraide.handicap.Entity.UserInfo;
import ma.entraide.handicap.Service.ProvinceService;
import ma.entraide.handicap.Service.UserInfoService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class HandicapApplication {
    @Autowired
    UserInfoService userInfoService;

    @Autowired
    ProvinceService provinceService;

    public static Logger logger = LoggerFactory.getLogger(HandicapApplication.class);

    public static void main(String[] args) {
        SpringApplication.run(HandicapApplication.class, args);
    }

    @Bean
    public CommandLineRunner runner() {
        return args ->{
            logger.info("Running Spring Security Application ...");

           /* Province agadir = provinceService.getProvinceById(1L);
            Province ainSebaa = provinceService.getProvinceById(2L);
            Province hoceima = provinceService.getProvinceById(3L);
            Province azilal = provinceService.getProvinceById(4L);
            Province benMisk = provinceService.getProvinceById(5L);
            Province beniMellal = provinceService.getProvinceById(6L);
            Province benSlimane = provinceService.getProvinceById(7L);
            Province boulemane = provinceService.getProvinceById(8L);
            Province casablancaAnfa = provinceService.getProvinceById(9L);
            Province chefchaouen = provinceService.getProvinceById(10L);
            Province chichaoua = provinceService.getProvinceById(11L);
            Province dakhla = provinceService.getProvinceById(12L);
            Province hajeb = provinceService.getProvinceById(13L);
            Province haouz = provinceService.getProvinceById(14L);
            Province elJadida = provinceService.getProvinceById(15L);
            Province kalaaSraghna = provinceService.getProvinceById(16L);
            Province errachidia = provinceService.getProvinceById(17L);
            Province essaouira = provinceService.getProvinceById(18L);
            Province fes = provinceService.getProvinceById(19L);
            Province figuig = provinceService.getProvinceById(20L);
            Province guelmim = provinceService.getProvinceById(21L);
            Province ifrane = provinceService.getProvinceById(22L);
            Province kenitra = provinceService.getProvinceById(23L);
            Province khemisset = provinceService.getProvinceById(24L);
            Province khénifra = provinceService.getProvinceById(25L);
            Province khribga = provinceService.getProvinceById(26L);
            Province laayoune = provinceService.getProvinceById(27L);
            Province larache = provinceService.getProvinceById(28L);
            Province marrakech = provinceService.getProvinceById(29L);
            Province meknes = provinceService.getProvinceById(30L);
            Province mohammedia = provinceService.getProvinceById(31L);
            Province nador = provinceService.getProvinceById(32L);
            Province ouarzazate = provinceService.getProvinceById(33L);
            Province oujda = provinceService.getProvinceById(34L);
            Province rabat = provinceService.getProvinceById(35L);
            Province safi = provinceService.getProvinceById(36L);
            Province sale = provinceService.getProvinceById(37L);
            Province settat = provinceService.getProvinceById(38L);
            Province inezganeAitMelloul = provinceService.getProvinceById(39L);
            Province sidiKacem = provinceService.getProvinceById(40L);
            Province tanTan = provinceService.getProvinceById(41L);
            Province tanger = provinceService.getProvinceById(42L);
            Province taounate = provinceService.getProvinceById(43L);
            Province taroudant = provinceService.getProvinceById(44L);
            Province tata = provinceService.getProvinceById(45L);
            Province taza = provinceService.getProvinceById(46L);
            Province temara = provinceService.getProvinceById(47L);
            Province tetouan = provinceService.getProvinceById(48L);
            Province tiznit = provinceService.getProvinceById(49L);
            Province assaZag = provinceService.getProvinceById(50L);
            Province smara = provinceService.getProvinceById(51L);
            Province boujdour = provinceService.getProvinceById(52L);
            Province jerada = provinceService.getProvinceById(53L);
            Province taourirt = provinceService.getProvinceById(54L);
            Province chtoukaAitBaha = provinceService.getProvinceById(55L);
            Province zagora = provinceService.getProvinceById(56L);
            Province fahsAnjra = provinceService.getProvinceById(57L);
            Province ainChock = provinceService.getProvinceById(58L);
            Province moulayYacoub = provinceService.getProvinceById(59L);
            Province sefrou = provinceService.getProvinceById(60L);
            Province mdiqFnideq = provinceService.getProvinceById(61L);
            Province berkane = provinceService.getProvinceById(62L);
            Province sidiBernoussi = provinceService.getProvinceById(63L);
            Province mediouna = provinceService.getProvinceById(64L);
            Province moulayRachid = provinceService.getProvinceById(65L);
            Province mersSultan = provinceService.getProvinceById(66L);
            Province hayHassani = provinceService.getProvinceById(67L);
            Province nouaceur = provinceService.getProvinceById(68L);
            Province guercif = provinceService.getProvinceById(69L);
            Province aousserd = provinceService.getProvinceById(70L);
            Province sidiBennour = provinceService.getProvinceById(71L);
            Province rehamna = provinceService.getProvinceById(72L);
            Province sidiSlimane = provinceService.getProvinceById(73L);
            Province midelt = provinceService.getProvinceById(74L);
            Province fquihBenSalah = provinceService.getProvinceById(75L);
            Province tarfaya = provinceService.getProvinceById(76L);
            Province drouch = provinceService.getProvinceById(77L);
            Province tinghir = provinceService.getProvinceById(78L);
            Province youssoufia = provinceService.getProvinceById(79L);
            Province berrechid = provinceService.getProvinceById(80L);
            Province ouezzane = provinceService.getProvinceById(81L);
            Province sidiIfni = provinceService.getProvinceById(82L);

            UserInfo user1 = new UserInfo(1,"Agadir","deleg.agadir@entraide.ma","USER_ROLES","ASH@delegation2024",agadir);
            UserInfo user2 = new UserInfo(2,"Ain Sebaa","deleg.ainsebaa@entraide.ma","USER_ROLES","ASH@delegation2024",ainSebaa);
            UserInfo user3 = new UserInfo(3,"Hoceima","deleg.hoceima@entraide.ma","USER_ROLES","ASH@delegation2024",hoceima);
            UserInfo user4 = new UserInfo(4,"Azilal","deleg.azilal@entraide.ma","USER_ROLES","ASH@delegation2024",azilal);
            UserInfo user5 = new UserInfo(5,"Ben M'Sik","deleg.benmisk@entraide.ma","USER_ROLES","ASH@delegation2024",benMisk);
            UserInfo user6 = new UserInfo(6,"Beni Mellal","deleg.benimellal@entraide.ma","USER_ROLES","ASH@delegation2024",beniMellal);
            UserInfo user7 = new UserInfo(7,"Benslimane","deleg.benslimane@entraide.ma","USER_ROLES","ASH@delegation2024",benSlimane);
            UserInfo user8 = new UserInfo(8,"Boulemane","deleg.boulemane@entraide.ma","USER_ROLES","ASH@delegation2024",boulemane);
            UserInfo user9 = new UserInfo(9,"Casablanca Anfa","deleg.casablanca.anfa@entraide.ma","USER_ROLES","ASH@delegation2024",casablancaAnfa);
            UserInfo user10 = new UserInfo(10,"Chefchaouen","deleg.chefchaouen@entraide.ma","USER_ROLES","ASH@delegation2024",chefchaouen);
            UserInfo user11 = new UserInfo(11,"Chichaoua","deleg.chichaoua@entraide.ma","USER_ROLES","ASH@delegation2024",chichaoua);
            UserInfo user12 = new UserInfo(12,"Dakhla","deleg.dakhla@entraide.ma","USER_ROLES","ASH@delegation2024",dakhla);
            UserInfo user13 = new UserInfo(13,"El Hajeb","deleg.elhajeb@entraide.ma","USER_ROLES","ASH@delegation2024",hajeb);
            UserInfo user14 = new UserInfo(14,"El Haouz","deleg.elhaouz@entraide.ma","USER_ROLES","ASH@delegation2024",haouz);
            UserInfo user15 = new UserInfo(15,"El Jadida","deleg.eljadida@entraide.ma","USER_ROLES","ASH@delegation2024",elJadida);
            UserInfo user16 = new UserInfo(16,"Kalaat Sraghna","deleg.kalaatsraghna@entraide.ma","USER_ROLES","ASH@delegation2024",kalaaSraghna);
            UserInfo user17 = new UserInfo(17,"Errachidia","deleg.errachidia@entraide.ma","USER_ROLES","ASH@delegation2024",errachidia);
            UserInfo user18 = new UserInfo(18,"Essaouira","deleg.essaouira@entraide.ma","USER_ROLES","ASH@delegation2024",essaouira);
            UserInfo user19 = new UserInfo(19,"Fès","deleg.fes@entraide.ma","USER_ROLES","ASH@delegation2024",fes);
            UserInfo user20 = new UserInfo(20,"Figuig","deleg.figuig@entraide.ma","USER_ROLES","ASH@delegation2024",figuig);
            UserInfo user21 = new UserInfo(21,"Guelmim","deleg.guelmim@entraide.ma","USER_ROLES","ASH@delegation2024",guelmim);
            UserInfo user22 = new UserInfo(22,"Ifrane","deleg.ifrane@entraide.ma","USER_ROLES","ASH@delegation2024",ifrane);
            UserInfo user23 = new UserInfo(23,"Kénitra","deleg.kenitra@entraide.ma","USER_ROLES","ASH@delegation2024",kenitra);
            UserInfo user24 = new UserInfo(24,"Khémisset","deleg.khemisset@entraide.ma","USER_ROLES","ASH@delegation2024",khemisset);
            UserInfo user25 = new UserInfo(25,"Khénifra","deleg.khenifra@entraide.ma","USER_ROLES","ASH@delegation2024",khénifra);
            UserInfo user26 = new UserInfo(26,"Khouribga","deleg.khouribga@entraide.ma","USER_ROLES","ASH@delegation2024",khribga);
            UserInfo user27 = new UserInfo(27,"Laâyoune","deleg.laayoune@entraide.ma","USER_ROLES","ASH@delegation2024",laayoune);
            UserInfo user28 = new UserInfo(28,"Larache","deleg.larache@entraide.ma","USER_ROLES","ASH@delegation2024",larache);
            UserInfo user29 = new UserInfo(29,"Marrakech","deleg.marrakech@entraide.ma","USER_ROLES","ASH@delegation2024",marrakech);
            UserInfo user30 = new UserInfo(30,"Meknès","deleg.meknes@entraide.ma","USER_ROLES","ASH@delegation2024",meknes);
            UserInfo user31 = new UserInfo(31,"Mohammédia","deleg.mohammedia@entraide.ma","USER_ROLES","ASH@delegation2024",mohammedia);
            UserInfo user32 = new UserInfo(32,"Nador","deleg.nador@entraide.ma","USER_ROLES","ASH@delegation2024",nador);
            UserInfo user33 = new UserInfo(33,"Ouarzazate","deleg.ouarzazate@entraide.ma","USER_ROLES","ASH@delegation2024",ouarzazate);
            UserInfo user34 = new UserInfo(34,"Oujda","deleg.oujda@entraide.ma","USER_ROLES","ASH@delegation2024",oujda);
            UserInfo user35 = new UserInfo(35,"Rabat","deleg.rabat@entraide.ma","USER_ROLES","ASH@delegation2024",rabat);
            UserInfo user36 = new UserInfo(36,"Safi","deleg.safi@entraide.ma","USER_ROLES","ASH@delegation2024",safi);
            UserInfo user37 = new UserInfo(37,"Salé","deleg.sale@entraide.ma","USER_ROLES","ASH@delegation2024",sale);
            UserInfo user38 = new UserInfo(38,"Settat","deleg.settat@entraide.ma","USER_ROLES","ASH@delegation2024",settat);
            UserInfo user39 = new UserInfo(39,"Inezgane Aït Melloul","deleg.inezgane@entraide.ma","USER_ROLES","ASH@delegation2024",inezganeAitMelloul);
            UserInfo user40 = new UserInfo(40,"Sidi Kacem","deleg.sidikacem@entraide.ma","USER_ROLES","ASH@delegation2024",sidiKacem);
            UserInfo user41 = new UserInfo(41,"Tan-Tan","deleg.tantan@entraide.ma","USER_ROLES","ASH@delegation2024",tanTan);
            UserInfo user42 = new UserInfo(42,"Tanger","deleg.tanger@entraide.ma","USER_ROLES","ASH@delegation2024",tanger);
            UserInfo user43 = new UserInfo(43,"Taounate","deleg.taounate@entraide.ma","USER_ROLES","ASH@delegation2024",taounate);
            UserInfo user44 = new UserInfo(44,"Taroudant","deleg.taroudant@entraide.ma","USER_ROLES","ASH@delegation2024",taroudant);
            UserInfo user45 = new UserInfo(45,"Tata","deleg.tata@entraide.ma","USER_ROLES","ASH@delegation2024",tata);
            UserInfo user46 = new UserInfo(46,"Taza","deleg.taza@entraide.ma","USER_ROLES","ASH@delegation2024",taza);
            UserInfo user47 = new UserInfo(47,"Témara","deleg.temara@entraide.ma","USER_ROLES","ASH@delegation2024",temara);
            UserInfo user48 = new UserInfo(48,"Tétouan","deleg.tetouan@entraide.ma","USER_ROLES","ASH@delegation2024",tetouan);
            UserInfo user49 = new UserInfo(49,"Tiznit","deleg.tiznit@entraide.ma","USER_ROLES","ASH@delegation2024",tiznit);
            UserInfo user50 = new UserInfo(50,"Assa-Zag","deleg.assazag@entraide.ma","USER_ROLES","ASH@delegation2024",assaZag);
            UserInfo user51 = new UserInfo(51,"Smara","deleg.smara@entraide.ma","USER_ROLES","ASH@delegation2024",smara);
            UserInfo user52 = new UserInfo(52,"Boujdour","deleg.boujdour@entraide.ma","USER_ROLES","ASH@delegation2024",boujdour);
            UserInfo user53 = new UserInfo(53,"Jerada","deleg.jerada@entraide.ma","USER_ROLES","ASH@delegation2024",jerada);
            UserInfo user54 = new UserInfo(54,"Taourirt","deleg.taourirt@entraide.ma","USER_ROLES","ASH@delegation2024",taourirt);
            UserInfo user55 = new UserInfo(55,"Chtouka Aït Baha","deleg.chtoukaaitbaha@entraide.ma","USER_ROLES","ASH@delegation2024",chtoukaAitBaha);
            UserInfo user56 = new UserInfo(56,"Zagora","deleg.zagora@entraide.ma","USER_ROLES","ASH@delegation2024",zagora);
            UserInfo user57 = new UserInfo(57,"Fahs-Anjra","deleg.fahsanjra@entraide.ma","USER_ROLES","ASH@delegation2024",fahsAnjra);
            UserInfo user58 = new UserInfo(58,"Aïn Chock","deleg.ainchock@entraide.ma","USER_ROLES","ASH@delegation2024",ainChock);
            UserInfo user59 = new UserInfo(59,"Moulay Yacoub","deleg.moulayyacoub@entraide.ma","USER_ROLES","ASH@delegation2024",moulayYacoub);
            UserInfo user60 = new UserInfo(60,"Sefrou","deleg.sefrou@entraide.ma","USER_ROLES","ASH@delegation2024",sefrou);
            UserInfo user61 = new UserInfo(61,"M'diq-Fnideq","deleg.mdiqfnideq@entraide.ma","USER_ROLES","ASH@delegation2024",mdiqFnideq);
            UserInfo user62 = new UserInfo(62,"Berkane","deleg.berkane@entraide.ma","USER_ROLES","ASH@delegation2024",berkane);
            UserInfo user63 = new UserInfo(63,"Sidi Bernoussi","deleg.sidibernoussi@entraide.ma","USER_ROLES","ASH@delegation2024",sidiBernoussi);
            UserInfo user64 = new UserInfo(64,"Médiouna","deleg.mediouna@entraide.ma","USER_ROLES","ASH@delegation2024",mediouna);
            UserInfo user65 = new UserInfo(65,"Moulay Rachid","deleg.moulayrachid@entraide.ma","USER_ROLES","ASH@delegation2024",moulayRachid);
            UserInfo user66 = new UserInfo(66,"Mers Sultan","deleg.merssultan@entraide.ma","USER_ROLES","ASH@delegation2024",mersSultan);
            UserInfo user67 = new UserInfo(67,"Hay Hassani","deleg.hayhassani@entraide.ma","USER_ROLES","ASH@delegation2024",hayHassani);
            UserInfo user68 = new UserInfo(68,"Nouaceur","deleg.nouaceur@entraide.ma","USER_ROLES","ASH@delegation2024",nouaceur);
            UserInfo user69 = new UserInfo(69,"Guercif","deleg.guercif@entraide.ma","USER_ROLES","ASH@delegation2024",guercif);
            UserInfo user70 = new UserInfo(70,"Aousserd","deleg.aousserd@entraide.ma","USER_ROLES","ASH@delegation2024",aousserd);
            UserInfo user71 = new UserInfo(71,"Sidi Bennour","deleg.sidibennour@entraide.ma","USER_ROLES","ASH@delegation2024",sidiBennour);
            UserInfo user72 = new UserInfo(72,"Rehamna","deleg.rehamna@entraide.ma","USER_ROLES","ASH@delegation2024",rehamna);
            UserInfo user73 = new UserInfo(73,"Sidi Slimane","deleg.sidislimane@entraide.ma","USER_ROLES","ASH@delegation2024",sidiSlimane);
            UserInfo user74 = new UserInfo(74,"Midelt","deleg.midelt@entraide.ma","USER_ROLES","ASH@delegation2024",midelt);
            UserInfo user75 = new UserInfo(75,"Fquih Ben Salah","deleg.fquihbensalah@entraide.ma","USER_ROLES","ASH@delegation2024",fquihBenSalah);
            UserInfo user76 = new UserInfo(76,"Tarfaya","deleg.tarfaya@entraide.ma","USER_ROLES","ASH@delegation2024",tarfaya);
            UserInfo user77 = new UserInfo(77,"Drouch","deleg.drouch@entraide.ma","USER_ROLES","ASH@delegation2024",drouch);
            UserInfo user78 = new UserInfo(78,"Tinghir","deleg.tinghir@entraide.ma","USER_ROLES","ASH@delegation2024",tinghir);
            UserInfo user79 = new UserInfo(79,"Youssoufia","deleg.youssoufia@entraide.ma","USER_ROLES","ASH@delegation2024",youssoufia);
            UserInfo user80 = new UserInfo(80,"Berrechid","deleg.berrechid@entraide.ma","USER_ROLES","ASH@delegation2024",berrechid);
            UserInfo user81 = new UserInfo(81,"Ouezzane","deleg.ouezzane@entraide.ma","USER_ROLES","ASH@delegation2024",ouezzane);
            UserInfo user82 = new UserInfo(82,"Sidi Ifni","deleg.sidiifni@entraide.ma","USER_ROLES","ASH@delegation2024",sidiIfni);

            userInfoService.addUser(user1);
            userInfoService.addUser(user2);
            userInfoService.addUser(user3);
            userInfoService.addUser(user4);
            userInfoService.addUser(user5);
            userInfoService.addUser(user6);
            userInfoService.addUser(user7);
            userInfoService.addUser(user8);
            userInfoService.addUser(user9);
            userInfoService.addUser(user10);
            userInfoService.addUser(user11);
            userInfoService.addUser(user12);
            userInfoService.addUser(user13);
            userInfoService.addUser(user14);
            userInfoService.addUser(user15);
            userInfoService.addUser(user16);
            userInfoService.addUser(user17);
            userInfoService.addUser(user18);
            userInfoService.addUser(user19);
            userInfoService.addUser(user20);
            userInfoService.addUser(user21);
            userInfoService.addUser(user22);
            userInfoService.addUser(user23);
            userInfoService.addUser(user24);
            userInfoService.addUser(user25);
            userInfoService.addUser(user26);
            userInfoService.addUser(user27);
            userInfoService.addUser(user28);
            userInfoService.addUser(user29);
            userInfoService.addUser(user30);
            userInfoService.addUser(user31);
            userInfoService.addUser(user32);
            userInfoService.addUser(user33);
            userInfoService.addUser(user34);
            userInfoService.addUser(user35);
            userInfoService.addUser(user36);
            userInfoService.addUser(user37);
            userInfoService.addUser(user38);
            userInfoService.addUser(user39);
            userInfoService.addUser(user40);
            userInfoService.addUser(user41);
            userInfoService.addUser(user42);
            userInfoService.addUser(user43);
            userInfoService.addUser(user44);
            userInfoService.addUser(user45);
            userInfoService.addUser(user46);
            userInfoService.addUser(user47);
            userInfoService.addUser(user48);
            userInfoService.addUser(user49);
            userInfoService.addUser(user50);
            userInfoService.addUser(user51);
            userInfoService.addUser(user52);
            userInfoService.addUser(user53);
            userInfoService.addUser(user54);
            userInfoService.addUser(user55);
            userInfoService.addUser(user56);
            userInfoService.addUser(user57);
            userInfoService.addUser(user58);
            userInfoService.addUser(user59);
            userInfoService.addUser(user60);
            userInfoService.addUser(user61);
            userInfoService.addUser(user62);
            userInfoService.addUser(user63);
            userInfoService.addUser(user64);
            userInfoService.addUser(user65);
            userInfoService.addUser(user66);
            userInfoService.addUser(user67);
            userInfoService.addUser(user68);
            userInfoService.addUser(user69);
            userInfoService.addUser(user70);
            userInfoService.addUser(user71);
            userInfoService.addUser(user72);
            userInfoService.addUser(user73);
            userInfoService.addUser(user74);
            userInfoService.addUser(user75);
            userInfoService.addUser(user76);
            userInfoService.addUser(user77);
            userInfoService.addUser(user78);
            userInfoService.addUser(user79);
            userInfoService.addUser(user80);
            userInfoService.addUser(user81);
            userInfoService.addUser(user82);

*/


            logger.info("end");
        };
    }
}
